spring.application.name=HospitalManagementWeb
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db
spring.datasource.username=root
spring.datasource.password=kavya
spring.jpa.hibernate.ddl-auto=update
server.port=8082

